removed datasource because it fails when bootstrapping new services and replaced it with manual ARN build (#42)
 ```
 module.service.module.code_deploy.aws_iam_role_policy_attachment.trigger[0]: Refreshing state... [id=xxx]

 Error: ECR Repository (xxx) not found
 ```

Co-authored-by: Matthias Naber <naber.matthias@gmail.com>