removed datasource because it fails when bootstrapping new services and replaced it with manual ARN build
```
module.service.module.code_deploy.aws_iam_role_policy_attachment.trigger[0]: Refreshing state... [id=xxx]
aremoved datasource because it fails when bootstrapping new services and replaced it with manual ARN build

 ```
 module.service.module.code_deploy.aws_iam_role_policy_attachment.trigger[0]: Refreshing state... [id=xxx]

 Error: ECR Repository (xxx) not found
 ```
Error: ECR Repository (xxx) not found
```